// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYslUyD1btVf4a4_-LM0ZuGbLfrMp14J4',
    appId: '1:960980823428:web:e5dc47e50ea4a9309fc1d1',
    messagingSenderId: '960980823428',
    projectId: 'portfolio-3c116',
    authDomain: 'portfolio-3c116.firebaseapp.com',
    storageBucket: 'portfolio-3c116.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK1w5lJoATtH-jdk1KSG-tjVI9EGd9sVI',
    appId: '1:960980823428:android:d8ee39fbc58b30fd9fc1d1',
    messagingSenderId: '960980823428',
    projectId: 'portfolio-3c116',
    storageBucket: 'portfolio-3c116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNTsjAvrynQAnAZMA5DNd9Iy9hoedsIc',
    appId: '1:960980823428:ios:f11bb136bc2537919fc1d1',
    messagingSenderId: '960980823428',
    projectId: 'portfolio-3c116',
    storageBucket: 'portfolio-3c116.appspot.com',
    iosBundleId: 'com.example.artfoio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNTsjAvrynQAnAZMA5DNd9Iy9hoedsIc',
    appId: '1:960980823428:ios:f11bb136bc2537919fc1d1',
    messagingSenderId: '960980823428',
    projectId: 'portfolio-3c116',
    storageBucket: 'portfolio-3c116.appspot.com',
    iosBundleId: 'com.example.artfoio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYslUyD1btVf4a4_-LM0ZuGbLfrMp14J4',
    appId: '1:960980823428:web:809dd19ebcaff4b49fc1d1',
    messagingSenderId: '960980823428',
    projectId: 'portfolio-3c116',
    authDomain: 'portfolio-3c116.firebaseapp.com',
    storageBucket: 'portfolio-3c116.appspot.com',
  );
}
